# Generated by Django 2.0.13 on 2019-10-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='nino',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
