# Generated by Django 2.0.13 on 2019-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0002_auto_20191009_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='grado_educativo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
