# Generated by Django 2.0.13 on 2019-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0003_auto_20191009_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivo_ingreso',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='motivo_ingreso',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='motivo_ingreso',
            name='nombre_motivo',
            field=models.CharField(max_length=60, verbose_name='Motivo de ingreso'),
        ),
    ]
