# Generated by Django 2.0.13 on 2019-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0004_auto_20191010_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='apellido_nino',
            field=models.CharField(max_length=60, verbose_name='Apellidos del niño'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='cui',
            field=models.CharField(max_length=60, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='fecha_evaluacion',
            field=models.DateField(verbose_name='Fecha de evaluación Biopsicosocial'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso a CANICA'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='grado_educativo',
            field=models.CharField(blank=True, choices=[('P', 'Primario'), ('Pr', 'Pre-Primario'), ('Ba', 'Básico'), ('D', 'Diversificado')], max_length=30, null=True, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='Fotografía del niño'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='lugar_nacimiento',
            field=models.CharField(max_length=60, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='lugar_residencia',
            field=models.CharField(max_length=60, verbose_name='Lugar de residencia'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='nombre_madre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo de la madre'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='nombre_nino',
            field=models.CharField(max_length=60, verbose_name='Nombres del niño'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='nombre_padre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo del padre'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Religión'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=3, verbose_name='Sexo'),
        ),
    ]
