# Generated by Django 2.0.13 on 2019-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0005_auto_20191010_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_dental',
            name='diagnostico',
            field=models.TextField(verbose_name='Dignóstico'),
        ),
        migrations.AlterField(
            model_name='area_dental',
            name='intervencion',
            field=models.TextField(verbose_name='Intervención médica'),
        ),
        migrations.AlterField(
            model_name='area_dental',
            name='proxima_cita',
            field=models.DateField(verbose_name='Próxima cita'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='altura',
            field=models.FloatField(verbose_name='Altura del niño'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='estado_piel',
            field=models.TextField(verbose_name='Estado de la piel'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='examen_sangre',
            field=models.BooleanField(verbose_name='Examen de sangre'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='examne_orina',
            field=models.BooleanField(verbose_name='Examen de orina'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='peso',
            field=models.IntegerField(verbose_name='Peso del niño'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='presencia_acaros',
            field=models.BooleanField(verbose_name='Presencia de acaros'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='presencia_piojos',
            field=models.BooleanField(verbose_name='Presencia de piojos'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='programa_vacunacion',
            field=models.BooleanField(verbose_name='Programa de vacunación'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='aspecto_clinico',
            field=models.TextField(null=True, verbose_name='Aspecto clínico'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='estado_emocional',
            field=models.TextField(null=True, verbose_name='Estado emocional'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_calidad_vida',
            field=models.BooleanField(verbose_name='Percepción de la calidad de vida en su hogar'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_situacion_desproteccion',
            field=models.BooleanField(verbose_name='Percepción de la situación de desprotección'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_temores_actuales',
            field=models.TextField(null=True, verbose_name='Percepción de temores actuales'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_temores_futuros',
            field=models.TextField(null=True, verbose_name='Percepción de temores futuros'),
        ),
        migrations.AlterField(
            model_name='area_social',
            name='recurso_familiar',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Recurso familiar'),
        ),
        migrations.AlterField(
            model_name='area_social',
            name='rol_familiar',
            field=models.TextField(blank=True, null=True, verbose_name='Rol familiar'),
        ),
        migrations.AlterField(
            model_name='area_social',
            name='visitas_autorizadas',
            field=models.BooleanField(verbose_name='Visitas Autorizadas'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='nombre_enfermedad',
            field=models.CharField(max_length=60, verbose_name='Nombre de la enfermedad'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='nombre_etnia',
            field=models.CharField(max_length=60, verbose_name='Nombre de la etnia'),
        ),
        migrations.AlterField(
            model_name='fuente_estre',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fuente_estre',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fuente_estre',
            name='nombre_fuente',
            field=models.CharField(max_length=60, verbose_name='Fuente de estrés'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre_idioma',
            field=models.CharField(max_length=60, verbose_name='Nombre del idioma'),
        ),
        migrations.AlterField(
            model_name='motivo_ingreso',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nivel_nutricion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nivel_nutricion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='nivel_nutricion',
            name='nivel',
            field=models.CharField(max_length=60, verbose_name='Nivel de nutrición'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='img', verbose_name='Fotografía de la notica'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo_noticia',
            field=models.CharField(max_length=40, verbose_name='Título de la noticia'),
        ),
        migrations.AlterField(
            model_name='relacion_familia',
            name='tipo_relacion',
            field=models.CharField(max_length=60, verbose_name='Tipo de relación familiar'),
        ),
    ]
