# Generated by Django 2.0.13 on 2019-10-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria_Producto',
                'verbose_name_plural': 'Categoria_Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='img')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('unidades', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='categoria_producto',
            name='producto',
            field=models.ManyToManyField(to='gestion_inventario.Producto'),
        ),
    ]
